services:
  - type: web
    name: yummy-uk
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
    disk:
      name: yummy-data
      mountPath: /opt/render/project/src
      sizeGB: 1
